# Generated by Django 2.2.7 on 2019-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('total_pontos', models.IntegerField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
