# Generated by Django 2.2.7 on 2019-11-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
    ]
