# Generated by Django 2.2.7 on 2019-11-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='myapp.Aluno'),
        ),
    ]
